#!/usr/bin/env python3
"""Writes the Phase 6 laptop wireframes (M2, docs/ui/laptop.md) to assets/ui/mocks/phase6/*.rml.

Literal data shaped like a mid-campaign game (day 12). Merc faces ("face-<n>") and item pictures
("shop-item-<n>") come from the player's game data at runtime; nothing derived from the game art is
written. Shown in game with ja2.debug("mock", "phase6/<name>"); screenshots: tests/e2e/manual/phase6_mocks.lua.
"""
import os

OUT = os.path.join(os.path.dirname(__file__), '..', '..', 'assets', 'ui', 'mocks', 'phase6')


def esc(s):
    return s.replace('&', '&amp;').replace('<', '&lt;').replace('>', '&gt;')


def icon(n, cls='icon'):
    return f'<img class="{cls}" src="icon-{n}"/>'


def kbd(k):
    return f'<span class="kbd">{k}</span>'


def btn(label, ic=None, k=None, cls='btn', id=None):
    i = f' id="{id}"' if id else ''
    return (f'<button class="{cls}"{i}>' + (icon(ic) if ic else '') + f'<span class="label">{label}</span>'
            + (kbd(k) if k else '') + '</button>')


def ibtn(ic, title, id=None, cls='icon-btn'):
    i = f' id="{id}"' if id else ''
    return f'<button class="{cls}"{i} title="{title}">{icon(ic)}</button>'


APPS = [  # id, icon, label, key, badge
    ('email', 'mail', 'E-mail', 'F1', '3'),
    ('web', 'globe', 'Web', 'F2', None),
    ('finances', 'money', 'Finances', 'F3', None),
    ('personnel', 'squad', 'Personnel', 'F4', None),
    ('history', 'history', 'History', 'F5', None),
    ('files', 'folder', 'Files', 'F6', '1'),
]


def shell(name, active, title, sub, content, foot=None):
    dock = ''.join(
        f'<div class="app{" active" if a == active else ""}" id="laptop.app.{a}" title="{lab} ({k})">{icon(ic)}'
        f'<span class="label">{lab}</span>{kbd(k)}' + (f'<span class="badge info">{b}</span>' if b else '') + '</div>'
        for a, ic, lab, k, b in APPS)
    dock += (f'<div class="app off" id="laptop.close" title="Close the laptop and go back to the map (Esc)">'
             f'{icon("power")}<span class="label">Close</span>{kbd("Esc")}</div>')
    footer = ''
    if foot:
        footer = '<div class="foot-hints">' + ''.join(
            (f'{kbd(k)}<span class="h">{h}</span>' if k else f'<span class="h dim">{h}</span>') for k, h in foot) + '</div>'
    return f'''<rml>
<head>
	<title>{esc(title)} (Phase 6 wireframe)</title>
	<link type="text/rcss" href="../../components.rcss"/>
	<link type="text/rcss" href="laptop.rcss"/>
</head>
<!-- M2 wireframe of the native laptop (docs/ui/laptop.md). Literal data.
     Generated by tools/ui/phase6_mocks.py: edit the generator, not this file. -->
<body class="lt">
<div class="lt-root">
	<div class="lt-bg"></div>
	<div class="lt-top">
		<div class="lt-os" title="sir-FER 4.0">{icon("laptop")}</div>
		<div class="lt-app"><span class="t" id="laptop.title">{title}</span><span class="s">{sub}</span></div>
		<div class="lt-stat" id="laptop.date"><span class="k">Day 12</span><span class="v">14:35</span></div>
		<div class="lt-stat" id="laptop.balance"><span class="k">Balance</span><span class="v">$48,250</span></div>
		<div class="lt-stat" id="laptop.team"><span class="k">Team</span><span class="v">9</span></div>
		<button class="icon-btn first-btn" id="laptop.help" title="Help (H)">{icon("question")}</button>
		{btn("Map", "map", "Esc", id="laptop.tomap")}
	</div>
	<div class="lt-dock" id="laptop.dock">{dock}</div>
	<div class="lt-win" id="laptop.window">
		<div class="lt-pad{" has-foot" if foot else ""}" style="padding: 0;">{content}</div>
		{footer}
	</div>
</div>
</body>
</rml>
'''


SITES = [  # id, label, css, host
    ('aim', 'A.I.M.', 'bm-aim', 'www.aim.com'),
    ('merc', 'M.E.R.C.', 'bm-merc', 'www.speck.com'),
    ('imp', 'I.M.P.', 'bm-imp', 'www.imp.com'),
    ('bobby', "Bobby Ray's", 'bm-bobby', 'www.bobbyrays.com'),
    ('florist', 'Florist', 'bm-florist', 'www.florist.com'),
    ('insurance', 'Insurance', 'bm-ins', 'www.mis-insurance.com'),
    ('funeral', 'Mortuary', 'bm-fun', 'www.mcgillicuttys.com'),
]


def browser(active, path, page, new=()):
    host = dict((s[0], s[3]) for s in SITES)[active]
    bms = ''.join(
        f'<div class="bm {css}{" active" if sid == active else ""}{" new" if sid in new else ""}" id="web.bookmark.{sid}">'
        f'<span class="sw"></span><span>{lab}</span>' + ('<span class="badge info">new</span>' if sid in new else '') + '</div>'
        for sid, lab, css, _ in SITES)
    return f'''<div class="br">
		<div class="br-bar">
			{ibtn("chevron-left", "Back (Alt+Left)", "web.back")}{ibtn("chevron-right", "Forward (Alt+Right)", "web.forward")}
			<div class="br-url" id="web.address">{icon("lock")}<span class="host">{host}</span><span>{path}</span></div>
			<div class="row grow" id="web.bookmarks">{bms}</div>
		</div>
		<div class="br-page page-{active}" id="web.page">{page}</div>
	</div>'''


def face(n, w):
    return f'<img src="face-{n}" style="width: {w}dp;"/>'


# ------------------------------------------------------------------------------------------------ desktop
def desktop():
    tiles = [
        ('email', 'mail', 'E-mail', '3 unread · latest from Enrico, Day 12', 'F1', '3', True),
        ('web', 'globe', 'Web', '7 bookmarks · Bobby Ray’s has a new shipment', 'F2', None, False),
        ('finances', 'money', 'Finances', '$48,250 · −$12,860 today', 'F3', None, False),
        ('personnel', 'squad', 'Personnel', '9 on the team · 1 contract ends today', 'F4', None, True),
        ('history', 'history', 'History', 'Liberated Drassen airport (Day 11)', 'F5', None, False),
        ('files', 'folder', 'Files', '1 new: Intel on Drassen', 'F6', '1', False),
    ]
    t = ''.join(
        f'<div class="tile{" hot" if hot else ""}" id="desktop.{a}">{icon(ic)}' + (f'<span class="badge info">{b}</span>' if b else '')
        + f'{kbd(k)}<span class="t">{lab}</span><span class="d">{d}</span></div>'
        for a, ic, lab, d, k, b, hot in tiles)
    notes = [
        ('mail', 'New mail from Enrico Chivaldori', 'Re: Drassen — keep the pressure on', '14:02'),
        ('contract', 'Steroid’s contract ends in 13 hours', 'Extend it from Personnel or the map', '13:00'),
        ('cart', 'Bobby Ray’s shipment arrived', '3 items waiting at Drassen airport', '08:00'),
        ('info', 'File received', 'Intel on Drassen from the R.I.S.', 'Day 11'),
    ]
    n = ''.join(f'<div class="notif">{icon(ic)}<div class="grow"><span class="t">{a}</span><span class="d">{b}</span></div><span class="w">{w}</span></div>' for ic, a, b, w in notes)
    sites = ''.join(f'<div class="site-tile {css}" id="desktop.site.{sid}"><span class="sw"></span><span class="t">{lab}</span><span class="h">{host}</span></div>' for sid, lab, css, host in SITES)
    c = f'''<div class="dk">
		<div class="dk-main">
			<span class="dk-hello">sir-FER 4.0 · Logged in · Day 12, 14:35</span>
			<span class="dk-title">Desktop</span>
			<div class="dk-tiles">{t}</div>
			<span class="section" style="margin-top: 16dp;">Web bookmarks</span>
			<div class="dk-sites">{sites}</div>
		</div>
		<div class="dk-side">
			<span class="section">Notifications</span>
			<div class="panel" id="desktop.notifications">{n}</div>
		</div>
	</div>'''
    return shell('desktop', None, 'Desktop', 'Choose a program', c,
                 foot=[('F1', 'mail'), ('F2', 'web'), ('Ctrl+Tab', 'switch program'), ('H', 'help'), ('Esc', 'back to the map')])


# ------------------------------------------------------------------------------------------------ email
MAILS = [
    ('Enrico Chivaldori', 'Re: Drassen — keep the pressure on', '12', 'unread'),
    ('Bobby Ray’s', 'Your order has shipped', '12', 'unread'),
    ('A.I.M.', 'Steroid — contract ending', '12', 'unread'),
    ('M.I.S. Insurance', 'Policy confirmation: Ivan, Lynx', '11', 'read'),
    ('Enrico Chivaldori', 'Drassen airport', '10', 'read'),
    ('I.M.P.', 'Your profile results', '3', 'read'),
    ('Speck T. Kline', 'M.E.R.C. is open for business!', '2', 'read'),
    ('Bobby Ray’s', 'Now open: Bobby Ray’s Guns ’n Things', '2', 'read'),
    ('A.I.M.', 'Hiring confirmation: Ivan Dolvich', '1', 'read'),
    ('Enrico Chivaldori', 'Inquiry', '1', 'read'),
    ('McGillicutty’s Mortuary', 'We are here for you', '1', 'read'),
]


def mail_rows(sel):
    return ''.join(
        f'<div class="tr {st}{" selected" if i == sel else ""}" id="email.mail[{i}]">'
        f'<div class="m-dot">{icon("ok") if st == "unread" else ""}</div><span class="m-from">{esc(f)}</span>'
        f'<span class="m-subj">{esc(s)}</span><span class="m-day">{d}</span></div>'
        for i, (f, s, d, st) in enumerate(MAILS))


def mail_list(full, sel):
    return f'''<div class="ml-list{" full" if full else ""}">
			<div class="ml-tools"><span class="strong">Inbox</span><span class="count">11 messages · 3 unread</span><span class="grow"></span>
				{btn("Delete", "remove", "Del", "btn btn-ghost", "email.delete")}</div>
			<div class="thead"><span class="th m-dot"></span><span class="th m-from" id="email.sort.from"><span>From</span></span><span class="th m-subj" id="email.sort.subject"><span>Subject</span></span><span class="th m-day sorted" id="email.sort.day"><span>Day</span>{icon("sort-desc")}</span></div>
			<div class="scroll" id="email.list">{mail_rows(sel)}</div>
		</div>'''


def email_inbox():
    c = f'<div class="ml">{mail_list(True, -1)}</div>'
    return shell('email', 'email', 'E-mail', '3 unread', c,
                 foot=[('Up', ''), ('Down', 'choose'), ('Enter', 'read'), ('Del', 'delete'), (None, 'Click a column to sort')])


def email_read():
    body = ''.join(f'<p>{esc(p)}</p>' for p in [
        'Good work at the airport. The whole of Drassen is talking about it, and so is Deidranna — expect her to send '
        'troops north before the week is out.',
        'The townspeople will only stand with us if they believe we can protect them. Train the militia, hold the town, '
        'and the mine’s income will start coming your way.',
        'I am sending the next payment now. Use it well.',
        'Enrico'])
    c = f'''<div class="ml">{mail_list(False, 0)}
		<div class="ml-read" id="email.reader">
			<div class="ml-rhead"><span class="ml-subject" id="email.subject">Re: Drassen — keep the pressure on</span>
				<div class="ml-meta"><span class="from">Enrico Chivaldori</span><span>Day 12, 14:02</span><span class="grow"></span><div class="pager" id="email.pages">{ibtn("chevron-left", "Previous page")}<span>Page 1 / 1</span>{ibtn("chevron-right", "Next page")}</div></div></div>
			<div class="ml-body">{body}
				<div class="ml-attach">{icon("money")}<div class="grow"><span class="strong">Payment received: $20,000</span><span class="dim">Added to your balance (Finances)</span></div>{btn("Finances", "chart", None, "btn btn-ghost")}</div>
			</div>
			<div class="ml-ract">{btn("Delete", "remove", "Del", "btn btn-danger", "email.read.delete")}<span class="grow"></span>{btn("Previous", "chevron-up", "Up", "btn", "email.prev")}{btn("Next", "chevron-down", "Down", "btn", "email.next")}{btn("Close", "close", "Esc", "btn", "email.close")}</div>
		</div></div>'''
    return shell('email', 'email', 'E-mail', '3 unread', c)


# ------------------------------------------------------------------------------------------------ A.I.M.
AIM = [  # profile, name, fee/day, status
    (0, 'Barry', '$700', ''), (1, 'Blood', '$950', ''), (2, 'Lynx', '$1,500', 'hired'), (3, 'Grizzly', '$1,100', ''),
    (4, 'Vicki', '$1,150', 'hired'), (5, 'Trevor', '$840', ''), (6, 'Grunty', '$1,320', ''), (7, 'Ivan', '$1,450', 'hired'),
    (8, 'Steroid', '$880', 'hired'), (9, 'Igor', '$450', ''), (10, 'Shadow', '$1,500', 'away'), (11, 'Red', '$1,850', ''),
    (12, 'Reaper', '$1,900', ''), (13, 'Fidel', '$1,100', 'hired'), (14, 'Fox', '$1,600', ''), (15, 'Sidney', '$2,200', ''),
    (16, 'Gus', '$3,000', ''), (17, 'Buns', '$1,350', 'hired'), (18, 'Ice', '$1,400', ''), (19, 'Spider', '$1,600', ''),
    (20, 'Cliff', '$1,150', ''), (21, 'Bull', '$1,050', ''), (22, 'Hitman', '$1,120', ''), (23, 'Buzz', '$1,920', 'dead'),
]
TAGS = {'hired': '<span class="tag ok">On your team</span>', 'away': '<span class="tag warn">On assignment</span>',
        'dead': '<span class="tag danger">Deceased</span>'}


def aim_head(on):
    links = ''.join(f'<span class="lk{" on" if l == on else ""}" id="aim.nav.{l.lower()}">{l}</span>' for l in ['Members', 'Alumni', 'Policies', 'History', 'Links'])
    return f'<div class="site-head"><span class="wm">A.I.M.</span><span class="wm-sub">Association of International Mercenaries</span><span class="grow"></span><div class="site-nav">{links}</div></div>'


def aim_members():
    cards = ''.join(
        f'<div class="mcard{" selected" if p == 0 else ""}{" " + st if st else ""}" id="aim.member[{p}]" title="{n}: {f} per day">'
        f'<div class="ph">{face(p, 192)}</div><div class="st">{TAGS.get(st, "")}</div><span class="nm">{n}</span>'
        f'<div class="meta"><span class="grow">Level {3 + p % 4}</span><span class="fee">{f}/day</span></div></div>'
        for p, n, f, st in AIM)
    chips = ''.join(f'<div class="chip{" on" if c == "Price" else ""}" id="aim.sort.{c.lower()}"><span>{c}</span>{icon("sort-asc") if c == "Price" else ""}</div>'
                    for c in ['Price', 'Experience', 'Marksmanship', 'Medical', 'Explosives', 'Mechanical'])
    page = f'''<div class="aim">{aim_head("Members")}
		<div class="aim-tools"><span class="lbl">Sort by</span>{chips}<span class="grow"></span><span class="lbl">Show</span><div class="chip on"><span>All 40</span></div><div class="chip"><span>Available</span></div></div>
		<div class="aim-grid" id="aim.members">{cards}</div></div>'''
    return shell('aim_members', 'web', 'Web', 'A.I.M. · Members', browser('aim', '/members?sort=price', page))


def aim_member():
    stats = [('Health', 83), ('Agility', 66), ('Dexterity', 72), ('Strength', 77), ('Leadership', 16), ('Wisdom', 61),
             ('Experience', 3), ('Marksmanship', 82), ('Mechanical', 46), ('Explosives', 57), ('Medical', 12)]
    srows = ''.join(f'<div class="srow"><span class="k">{k}</span><div class="bar"><div class="fill" style="width: {v}%"></div></div><span class="v">{v}</span></div>' for k, v in stats)
    gear = '<span class="section" style="margin-top: 16dp;">Optional gear · $1,455</span><div class="gear" id="aim.member.gear">' + ''.join(f'<div class="gi" title="{n}"><div class="pic"><img src="shop-item-{i}"/></div><span>{n}</span></div>' for i, n in [(176, 'Steel Helmet'), (161, 'Flak Jacket'), (5, '.38 S&amp;W'), (77, '.38 ammo ×5'), (137, 'TNT'), (223, 'Detonator'), (204, 'Locksmith Kit')]) + '</div>'
    page = f'''<div class="aim">{aim_head("Members")}
		<div class="aim-page">
			<div class="aim-face"><div class="ph" id="aim.member.face">{face(0, 288)}</div>
				<div class="nav">{btn("Prev", "chevron-left", None, "btn", "aim.member.prev")}{btn("Next", "chevron-right", None, "btn", "aim.member.next")}</div></div>
			<div class="aim-info">
				<span class="aim-name" id="aim.member.name">Barry</span><span class="aim-full">Barry Unger · Level 3 · Active member · Germany</span>
				<div class="aim-cols"><div class="aim-stats" id="aim.member.stats">{srows}</div>
					<div class="aim-bio grow"><span class="section">Additional info</span>
						<p>Barry’s Bavarian homeland gave him a love of the outdoors and a passion for explosives. Barry’s known for keeping a cool head and a short temper.</p>
						{gear}
						<div class="fees" id="aim.member.fees"><div class="fee-c"><span class="k">One day</span><span class="v">$700</span></div><div class="fee-c on"><span class="k">One week</span><span class="v">$3,400</span></div><div class="fee-c"><span class="k">Two weeks</span><span class="v">$5,500</span></div></div>
						<div class="row" style="margin-top: 12dp;"><span class="tag info">No medical deposit</span></div>
					</div></div>
			</div>
			<div class="vc" id="aim.hire">
				<div class="vc-head">{icon("video")}<span class="t">Video conference · Barry</span>{ibtn("close", "Hang up (Esc)", "aim.hire.hangup")}</div>
				<div class="vc-feed"><div class="ph">{face(0, 96)}</div><div class="say">“Barry Unger here. You want to talk business? I’m listening.”</div></div>
				<div class="vc-body">
					<span class="section">Contract length</span>
					<div class="seg" id="aim.hire.length"><div class="o"><span class="a">One day</span><span class="b">$700</span></div><div class="o on"><span class="a">One week</span><span class="b">$3,400</span></div><div class="o"><span class="a">Two weeks</span><span class="b">$5,500</span></div></div>
					<span class="section">Gear</span>
					<div class="seg" id="aim.hire.gear"><div class="o"><span class="a">No equipment</span><span class="b">$0</span></div><div class="o on"><span class="a">Buy equipment</span><span class="b">$1,455</span></div></div>
					<div class="vc-sum"><div class="kv"><span class="k">Contract, one week</span><span class="v">$3,400</span></div><div class="kv"><span class="k">Equipment</span><span class="v">$1,455</span></div><div class="kv"><span class="k">Medical deposit</span><span class="v">&#8212;</span></div><div class="kv total"><span class="k">Contract charge</span><span class="v">$4,855</span></div><div class="kv"><span class="k">Balance after</span><span class="v">$43,395</span></div></div>
				</div>
				<div class="vc-act">{btn("Hang up", None, "Esc", "btn", "aim.hire.cancel")}{btn("Transfer funds", "money", "Enter", "btn btn-primary", "aim.hire.transfer")}</div>
			</div>
		</div></div>'''
    return shell('aim_member', 'web', 'Web', 'A.I.M. · Barry', browser('aim', '/members/barry', page))


# ------------------------------------------------------------------------------------------------ M.E.R.C.
MERC = [(40, 'Biff', 'Biff Apscott', 'Level 2', '$300', [('MRK', 45), ('MED', 12), ('MEC', 6), ('EXP', 2), ('LDR', 7)], 'hired'),
        (44, 'Flo', 'Florence Gabriel', 'Level 2', '$420', [('MRK', 60), ('MED', 36), ('MEC', 10), ('EXP', 5), ('LDR', 18)], ''),
        (41, 'Haywire', 'Edgar Smorth', 'Level 3', '$520', [('MRK', 71), ('MED', 4), ('MEC', 40), ('EXP', 75), ('LDR', 12)], ''),
        (43, 'Razor', 'Eric Weddington', 'Level 3', '$600', [('MRK', 70), ('MED', 8), ('MEC', 14), ('EXP', 20), ('LDR', 40)], ''),
        (42, 'Gasket', 'Lance Fisher', 'Level 3', '$640', [('MRK', 48), ('MED', 5), ('MEC', 86), ('EXP', 40), ('LDR', 4)], '')]


def merc():
    rows = ''
    for i, (p, n, full, lvl, fee, sk, st) in enumerate(MERC):
        sks = ''.join(f'<div class="s"><span class="k">{k}</span><span class="v">{v}</span></div>' for k, v in sk)
        act = '<span class="tag ok">Hired</span>' if st == 'hired' else btn('Hire', 'add', None, 'btn-site', f'merc.hire[{i}]')
        rows += (f'<div class="mrow{" selected" if i == 1 else ""}" id="merc.merc[{i}]"><div class="ph">{face(p, 96)}</div>'
                 f'<div class="who"><span class="n">{n}</span><span class="d">{full} · {lvl}</span></div><div class="sk">{sks}</div>'
                 f'<div class="pr"><span class="v">{fee}</span><span class="k">per day · no contract</span></div><div class="act">{act}</div></div>')
    page = f'''<div class="merc"><div class="site-head"><span class="wm">M.E.R.C.</span><span class="wm-sub">More Economic Recruiting Center</span><span class="grow"></span>
			<div class="site-nav"><span class="lk on" id="merc.nav.files">Files</span><span class="lk" id="merc.nav.account">Account</span></div></div>
		<div class="site-body">
			<div class="speck"><div class="vid" id="merc.speck"><div class="ph" style="width: 192dp; height: 212dp; decorator: image(gen-silhouette);"></div></div>
				<div class="bubble">“Flo! A sweetheart with a rifle, and cheap too. Now’s the time, my friend — and don’t forget, your account’s due Friday!”</div>
				<div class="acct" id="merc.account"><span class="section">Your account</span>
					<div class="kv"><span class="k">Mercs on the team</span><span class="v">1</span></div>
					<div class="kv"><span class="k">Owed (paid daily)</span><span class="v">$300</span></div>
					<div class="kv"><span class="k">Account status</span><span class="v ok-t">Good standing</span></div>
				</div></div>
			<div class="mfiles" id="merc.files">{rows}</div>
		</div></div>'''
    return shell('merc', 'web', 'Web', 'M.E.R.C. · Files', browser('merc', '/files', page))


# ------------------------------------------------------------------------------------------------ I.M.P.
def imp_quiz():
    steps = [('1', 'Begin', 'done'), ('2', 'Personality', 'on'), ('3', 'Attributes', ''), ('4', 'Specialties', ''), ('5', 'Portrait', ''), ('6', 'Voice', ''), ('7', 'Finish', '')]
    st = ''.join(f'<div class="step {c}"><span class="n">{n}</span><span>{l}</span></div>' for n, l, c in steps)
    prog = ''.join(f'<div class="p{" done" if i < 5 else (" on" if i == 5 else "")}"></div>' for i in range(16))
    answers = ['Stay put and wait for the others to catch up — nobody runs off alone.',
               'Take point. Somebody has to, and I trust myself most.',
               'Hang back and cover the squad from a good firing position.',
               'Whatever the leader says. That’s what a chain of command is for.',
               'Find the nearest bar. The war will still be there tomorrow.']
    ans = ''.join(f'<div class="ans{" on" if i == 1 else ""}" id="imp.answer[{i}]">{kbd(str(i + 1))}<span class="t">{a}</span>{icon("ok") if i == 1 else ""}</div>' for i, a in enumerate(answers))
    page = f'''<div class="imp"><div class="site-head"><span class="wm">I.M.P.</span><span class="wm-sub">Institute for Mercenary Profiling</span><span class="grow"></span>{btn("Cancel", "close", None, "btn btn-ghost", "imp.cancel")}</div>
		<div class="imp-steps" id="imp.steps">{st}</div>
		<div class="quiz">
			<div class="quiz-main">
				<span class="q-no">Question 6 of 16</span><div class="q-prog">{prog}</div>
				<span class="q-text" id="imp.question">Your squad is pinned down at the edge of town. You have a few seconds to decide. What do you do?</span>
				<div id="imp.answers">{ans}</div>
				<div class="q-act">{btn("Previous", "chevron-left", "Left", "btn", "imp.prev")}{btn("Start over", "reload", None, "btn btn-ghost", "imp.restart")}<span class="grow"></span>{btn("Confirm answer", "confirm", "Enter", "btn btn-primary", "imp.confirm")}</div>
			</div>
			<div class="quiz-side"><div class="panel pad"><span class="section">Your profile</span>
				<div class="kv"><span class="k">Name</span><span class="v">Kat Rourke</span></div>
				<div class="kv"><span class="k">Nickname</span><span class="v">Kat</span></div>
				<div class="kv"><span class="k">Gender</span><span class="v">Female</span></div>
				<div class="kv"><span class="k">Profile fee</span><span class="v">$3,000</span></div>
				<p class="dim" style="display: block; margin-top: 12dp; font-size: 15dp; line-height: 21dp;">There are no right answers. Your answers decide your character’s personality and attitude, which other mercs will react to.</p>
			</div></div>
		</div></div>'''
    return shell('imp_quiz', 'web', 'Web', 'I.M.P. · Personality', browser('imp', '/profile/personality', page))


# ------------------------------------------------------------------------------------------------ Bobby Ray's
GUNS = [(4, 'Beretta 93R', '9mm', '1.1 kg', '15', '22', '120 m', '1100/min', '$470', 2, 0, 'The most pistol you’ll ever need. Classified as a machine pistol, it has a fold-down front grip and a shoulder stock for three-round bursts.'),
        (1, 'Glock 17', '9mm', '0.6 kg', '15', '21', '120 m', '40/min', '$350', 7, 2, 'Most of this Austrian pistol’s parts are plastic, but it will still be found by airport X-ray machines. Common army issue worldwide.'),
        (7, '.357 Desert Eagle', '.357 cal', '1.7 kg', '9', '24', '135 m', '27/min', '$300', 5, 0, 'This single-action, gas-operated pistol is one hundred per cent U.S. made, with a rotating bolt for positive lock-up.'),
        (5, '.38 S&W Special', '.38 cal', '1.1 kg', '6', '22', '130 m', '25/min', '$250', 1, 1, 'The standard Smith and Wesson military and police revolver: ideal for self-defence, prone to light hammer blows as the mainspring ages.')]


def bob_head(on):
    links = ''.join(f'<span class="lk{" on" if l == on else ""}" id="bobby.nav.{l.lower()}">{l}</span>' for l in ['Shop', 'Order form', 'Shipments'])
    return f'<div class="site-head"><span class="wm">Bobby Ray’s</span><span class="wm-sub">Guns ’n Things · since 1979</span><span class="grow"></span><div class="site-nav">{links}</div></div>'


def bobby_shop():
    cats = ''.join(f'<div class="chip{" on" if c == "Guns" else ""}" id="bobby.cat.{c.lower()}"><span>{c}</span></div>' for c in ['Guns', 'Ammo', 'Armor', 'Misc.', 'Used'])
    prods = ''
    for i, (it, n, cal, w, mag, dam, rng, rof, pr, stock, q, desc) in enumerate(GUNS):
        prods += (f'<div class="prod{" in-cart" if q else ""}" id="bobby.item[{i}]"><div class="pic"><img src="shop-item-{it}"/></div>'
                  f'<div class="info"><span class="n">{n}</span><div class="specs"><span class="s">Cal <span class="v">{cal}</span></span><span class="s">Mag <span class="v">{mag}</span></span>'
                  f'<span class="s">Dam <span class="v">{dam}</span></span><span class="s">Rng <span class="v">{rng}</span></span><span class="s">ROF <span class="v">{rof}</span></span><span class="s">Wt <span class="v">{w}</span></span><span class="s">In stock <span class="v">{stock}</span></span></div>'
                  f'<span class="desc">{esc(desc)}</span></div>'
                  f'<div class="price"><span class="v">{pr}</span><span class="k">each</span></div>'
                  f'<div class="qty">{ibtn("remove", "One less (right-click)")}<span class="n">{q}</span>{ibtn("add", "One more (click)")}</div></div>')
    cart = f'''<div class="cart" id="bobby.cart"><div class="cart-head">{icon("cart")}<span class="t">Order</span><span class="dim">8 of 10 items</span></div>
			<div class="cline"><span class="q">2×</span><span class="n">Glock 17</span><span class="p">$700</span></div>
			<div class="cline"><span class="q">1×</span><span class="n">.38 S&amp;W Special</span><span class="p">$250</span></div>
			<div class="cline"><span class="q">5×</span><span class="n">9mm 15-round magazine</span><span class="p">$100</span></div>
			<div class="cart-foot"><div class="kv"><span class="k">Subtotal</span><span class="v">$1,050</span></div><div class="kv"><span class="k">Weight</span><span class="v">2.8 kg</span></div>
			<button class="btn-site" id="bobby.toorder">{icon("cart")}<span>Order form</span></button></div></div>'''
    page = f'''<div class="bob">{bob_head("Shop")}
		<div class="bob-cats">{cats}<span class="grow"></span><div class="chip"><span>Sort: price</span>{icon("sort-asc")}</div></div>
		<div class="bob-main"><div class="bob-list" id="bobby.items">{prods}</div>{cart}</div></div>'''
    return shell('bobby_shop', 'web', 'Web', "Bobby Ray's · Guns", browser('bobby', '/guns', page))


def bobby_order():
    lines = [('2', 'Glock 17', '1.2', '$350', '$700'), ('1', '.38 S&W Special', '1.1', '$250', '$250'), ('5', '9mm 15-round magazine', '0.5', '$20', '$100'),
             ('1', 'Kevlar Vest *', '2.4', '$190', '$190')]
    rows = ''.join(f'<div class="tr" id="bobby.order.line[{i}]"><div class="c-q row">{ibtn("remove", "One less")}<span class="mono" style="width: 28dp; text-align: center;">{q}</span>{ibtn("add", "One more")}</div>'
                   f'<span class="c-n">{esc(n)}</span><span class="c-w num">{w} kg</span><span class="c-u num">{u}</span><span class="c-t num">{t}</span><div class="c-x">{ibtn("close", "Remove")}</div></div>' for i, (q, n, w, u, t) in enumerate(lines))
    speeds = [('Overnight Express', '$20 / kg', False), ('2 Business Days', '$15 / kg', True), ('Standard Service', '$10 / kg', False)]
    sp = ''.join(f'<div class="radio{" on" if on else ""}" id="bobby.order.speed[{i}]"><span class="dot"></span><span class="t">{n}</span><span class="v">{p}</span></div>' for i, (n, p, on) in enumerate(speeds))
    page = f'''<div class="bob">{bob_head("Order form")}
		<div class="of">
			<div class="of-items"><div class="thead"><span class="th c-q"><span>Qty</span></span><span class="th c-n"><span>Item</span></span><span class="th c-w"><span class="grow"></span><span>Weight</span></span><span class="th c-u"><span class="grow"></span><span>Unit price</span></span><span class="th c-t"><span class="grow"></span><span>Total</span></span><span class="th c-x"></span></div>{rows}
				<div class="row" style="margin-top: 12dp;"><span class="dim grow">* Used item · max 10 items per order</span>{btn("Clear order", "remove", None, "btn btn-ghost", "bobby.order.clear")}{btn("Back to the shop", "chevron-left", None, "btn", "bobby.order.back")}</div></div>
			<div class="of-side">
				<div class="panel pad"><span class="section">Delivery location</span><div class="dd" id="bobby.order.city"><span class="t">Drassen (airport)</span>{icon("chevron-down")}</div>
					<span class="dim" style="display: block; margin-top: 8dp; font-size: 15dp;">Only towns with an airport you control. Rates depend on the destination.</span></div>
				<div class="panel pad"><span class="section">Shipping speed</span>{sp}</div>
				<div class="panel pad" id="bobby.order.totals"><div class="kv"><span class="k">Subtotal</span><span class="v">$1,240</span></div><div class="kv"><span class="k">Package weight (min. 2 kg)</span><span class="v">5.2 kg</span></div><div class="kv"><span class="k">Shipping &amp; handling</span><span class="v">$78</span></div>
					<div class="kv total"><span class="k">Grand total</span><span class="v">$1,318</span></div>
					<button class="btn btn-primary" id="bobby.order.accept" style="width: 100%; margin-top: 12dp;">{icon("confirm")}<span class="label">Accept order</span>{kbd("Enter")}</button></div>
			</div></div></div>'''
    return shell('bobby_order', 'web', 'Web', "Bobby Ray's · Order form", browser('bobby', '/order', page))


# ------------------------------------------------------------------------------------------------ finances
def finances():
    tx = [('12', 'Mine income: Drassen', '$3,450', '', '$48,250'), ('12', 'Ext. Steroid’s contract by 1 week', '', '$6,160', '$44,800'),
          ('12', 'Bobby Ray purchase', '', '$2,490', '$50,960'), ('12', 'Transfer funds from Enrico', '$20,000', '', '$53,450'),
          ('12', 'Payment to Skyrider', '', '$1,700', '$33,450'), ('11', 'Mine income: Drassen', '$3,450', '', '$35,150'),
          ('11', 'Purchased insurance for Ivan', '', '$1,290', '$31,700'), ('11', 'Medical deposit for Fidel', '', '$400', '$32,990'),
          ('11', 'Hired Fidel from AIM', '', '$7,700', '$33,390'), ('10', 'Settled accounts at M.E.R.C.', '', '$2,100', '$41,090'),
          ('10', 'Anonymous deposit', '$5,000', '', '$43,190'), ('10', 'Mine income: Drassen', '$2,800', '', '$38,190')]
    rows, last = '', None
    for i, (d, t, cr, db, bal) in enumerate(tx):
        if d != last:
            rows += f'<div class="daysep"><span>Day {d}</span></div>'
            last = d
        rows += (f'<div class="tr" id="finances.tx[{i}]"><span class="c-day">Day {d}</span><span class="c-tx">{esc(t)}</span>'
                 f'<span class="c-cr">{cr}</span><span class="c-db">{db}</span><span class="c-bal">{bal}</span></div>')
    bars = ''.join(f'<div class="b{" neg" if v < 0 else ""}" style="height: {abs(v)}%;"></div>' for v in [30, 22, -60, 45, 28, -35, 52, 40, -80, 60, 35, 48])
    c = f'''<div class="fin">
		<div class="fin-cards" id="finances.summary">
			<div class="fcard hl"><span class="k">Current balance</span><span class="v">$48,250</span><span class="d">Day 12, 14:35</span></div>
			<div class="fcard"><span class="k">Today’s income</span><span class="v ok-t">+$3,450</span><span class="d">+$20,000 other deposits</span></div>
			<div class="fcard"><span class="k">Today’s debits</span><span class="v danger-t">−$10,350</span><span class="d">Contracts, shop, Skyrider</span></div>
			<div class="fcard"><span class="k">Forecast income</span><span class="v">+$3,450</span><span class="d">Mines, at today’s loyalty</span></div>
			<div class="fcard last"><span class="k">Projected balance</span><span class="v">$51,700</span><span class="d">End of tomorrow</span></div>
		</div>
		<div class="fin-main">
			<div class="ledger panel"><div class="thead"><span class="th c-day sorted"><span>Day</span>{icon("sort-desc")}</span><span class="th c-tx"><span>Transaction</span></span><span class="th c-cr"><span class="grow"></span><span>Credit</span></span><span class="th c-db"><span class="grow"></span><span>Debit</span></span><span class="th c-bal"><span class="grow"></span><span>Balance</span></span></div>
				<div class="scroll" id="finances.ledger">{rows}</div></div>
			<div class="fin-side">
				<div class="panel pad"><span class="section">Yesterday (Day 11)</span>
					<div class="kv"><span class="k">Actual income</span><span class="v ok-t">$3,450</span></div><div class="kv"><span class="k">Other deposits</span><span class="v">$0</span></div>
					<div class="kv"><span class="k">Debits</span><span class="v danger-t">$9,390</span></div><div class="kv total"><span class="k">Balance at day’s end</span><span class="v">$35,150</span></div></div>
				<div class="panel pad"><span class="section">Balance, last 12 days</span><div class="spark" id="finances.chart">{bars}</div></div>
			</div>
		</div></div>'''
    return shell('finances', 'finances', 'Finances', 'Bookkeeper Plus', c,
                 foot=[('PgUp', ''), ('PgDn', 'page'), ('Home', ''), ('End', 'first / last'), (None, '212 transactions since Day 1')])


# ------------------------------------------------------------------------------------------------ personnel
TEAM = [(7, 'Ivan', 'Squad 1 · B13', 82, '5.3d'), (3, 'Grizzly', 'Squad 1 · B13', 95, '5.3d'), (2, 'Lynx', 'Squad 1 · B13', 60, '2.1d'),
        (13, 'Fidel', 'Squad 2 · C13', 100, '6.0d'), (17, 'Buns', 'Squad 2 · C13', 88, '6.0d'), (8, 'Steroid', 'Squad 2 · C13', 91, '13h'),
        (4, 'Vicki', 'Doctor · B13', 100, '3.4d'), (0, 'Barry', 'Train militia · C13', 74, '4.0d'), (40, 'Biff', 'In transit · M.E.R.C.', 100, '—')]


def personnel():
    rows = ''.join(
        f'<div class="prow{" selected" if i == 0 else ""}" id="personnel.merc[{i}]"><div class="ph">{face(p, 48)}</div>'
        f'<div class="who"><span class="n">{n}</span><span class="d">{d}</span></div>'
        f'<div class="hp"><div class="bar hp"><div class="fill" style="width: {hp}%"></div></div></div><span class="c{" warn-t" if c == "13h" else ""}">{c}</span></div>'
        for i, (p, n, d, hp, c) in enumerate(TEAM))
    attrs = [('Health', '74 / 90', ''), ('Agility', '83', ''), ('Dexterity', '88', ''), ('Strength', '86', ''), ('Leadership', '45', ''), ('Wisdom', '83', ''),
             ('Level', '5', '+1'), ('Marksmanship', '91', '+3'), ('Mechanical', '45', ''), ('Explosives', '22', ''), ('Medical', '12', '')]
    a1 = ''.join(f'<div class="attr2"><span class="k">{k}</span><span class="v">{v}</span>' + (f'<span class="up">{u}</span>' if u else '') + '</div>' for k, v, u in attrs)
    emp = [('Daily cost', '$1,450'), ('Contract', 'One week'), ('Remaining contract', '5.3 days'), ('Total cost to date', '$15,950'),
           ('Total service', '11 days'), ('Medical deposit', '$400'), ('Insured', 'Yes, until Day 19')]
    rec = [('Kills', '14'), ('Assists', '6'), ('Hit percentage', '61%'), ('Battles', '5'), ('Times wounded', '2')]
    e = ''.join(f'<div class="attr2"><span class="k">{k}</span><span class="v">{v}</span></div>' for k, v in emp)
    r = ''.join(f'<div class="attr2"><span class="k">{k}</span><span class="v">{v}</span></div>' for k, v in rec)
    c = f'''<div class="per">
		<div class="per-roster"><div class="tabs" id="personnel.tabs"><span class="tab active" id="personnel.tab.current">Current team (9)</span><span class="tab" id="personnel.tab.departed">Departed (2)</span></div>
			<div class="scroll" id="personnel.roster">{rows}</div>
			<div class="per-team" id="personnel.teamstats"><span class="section">Team</span><div class="kv"><span class="k">Daily cost</span><span class="v">$10,120</span></div><div class="kv"><span class="k">Highest marksmanship</span><span class="v">Ivan 91</span></div><div class="kv"><span class="k">Lowest health</span><span class="v">Lynx 60%</span></div></div></div>
		<div class="per-detail">
			<div class="pd-head"><div class="pd-face" id="personnel.face">{face(7, 192)}</div>
				<div class="pd-id"><span class="pd-name">Ivan</span><span class="pd-full">Ivan Dolvich · A.I.M. · Squad 1, B13 Drassen</span>
					<div class="stat"><span class="k">HP</span><span class="bar hp"><span class="fill" style="width: 82%"></span><span class="lost" style="width: 6%"></span></span><span class="v">74/90</span></div>
					<div class="stat"><span class="k">EN</span><span class="bar breath"><span class="fill" style="width: 64%"></span></span><span class="v">64</span></div>
					<div class="stat"><span class="k">MOR</span><span class="bar morale"><span class="fill" style="width: 70%"></span></span><span class="v">Good</span></div>
					<div class="row" style="margin-top: 8dp;"><span class="tag">Skills: Auto weapons</span></div></div></div>
			<div class="tabs pd-tabs" id="personnel.view"><span class="tab active" id="personnel.view.stats">Stats</span><span class="tab" id="personnel.view.employment">Employment</span><span class="tab" id="personnel.view.inventory">Inventory</span></div>
			<div class="pd-body"><div class="pd-col"><span class="section">Attributes</span>{a1}</div><div class="pd-col"><span class="section">Employment</span>{e}</div><div class="pd-col last"><span class="section">Record</span>{r}</div></div>
		</div></div>'''
    return shell('personnel', 'personnel', 'Personnel', 'Current team · 9 mercs', c,
                 foot=[('Up', ''), ('Down', 'choose merc'), ('Tab', 'stats / employment / inventory'), (None, 'Right-click a merc for the map screen')])


MOCKS = {'desktop': desktop, 'email_inbox': email_inbox, 'email_read': email_read, 'aim_members': aim_members,
         'aim_member': aim_member, 'merc': merc, 'imp_quiz': imp_quiz, 'bobby_shop': bobby_shop,
         'bobby_order': bobby_order, 'finances': finances, 'personnel': personnel}

if __name__ == '__main__':
    os.makedirs(OUT, exist_ok=True)
    for name, fn in MOCKS.items():
        with open(os.path.join(OUT, name + '.rml'), 'w', encoding='utf-8', newline='\n') as f:
            f.write(fn())
    print('wrote', len(MOCKS), 'mocks to', os.path.normpath(OUT))
